import { createSlice } from "@reduxjs/toolkit";

// Define a slice for members
const collegesSlice = createSlice({
  name: "college",
  initialState: { colleges: [] },
  reducers: {
    setColleges: (state, action) => {
      state.colleges = action.payload;
    },
    getColleges: (state, action) => {
      return { ...state, ...action.payload };
    },
  },
});

// Export actions generated by the slice
export const { setColleges, getColleges } = collegesSlice.actions;

// Export the reducer
export default collegesSlice.reducer;
