import { createSlice } from "@reduxjs/toolkit";

// Define a slice for members
const coursesSlice = createSlice({
  name: "course",
  initialState: { courses: [] },
  reducers: {
    setCourses: (state, action) => {
      state.courses = action.payload;
    },
    getCourses: (state, action) => {
      return { ...state, ...action.payload };
    },
  },
});

// Export actions generated by the slice
export const { setCourses, getCourses } = coursesSlice.actions;

// Export the reducer
export default coursesSlice.reducer;
