import { createSlice } from "@reduxjs/toolkit";

// Define a slice for members
const subjectsSlice = createSlice({
  name: "subject",
  initialState: { subjects: [] },
  reducers: {
    setSubjects: (state, action) => {
      state.subjects = action.payload;
    },
    getSubjects: (state, action) => {
      return { ...state, ...action.payload };
    },
  },
});

// Export actions generated by the slice
export const { setSubjects, getSubjects } = subjectsSlice.actions;

// Export the reducer
export default subjectsSlice.reducer;
